<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HelloLaravel extends Controller
{
    
    public function __invoke(){
        $data = json_decode('[{
            "id": 1,
            "first_name": "Paige",
            "last_name": "Beaves",
            "email": "pbeaves0@businesswire.com",
            "gender": "Female"
          }, {
            "id": 2,
            "first_name": "Zaria",
            "last_name": "Pardy",
            "email": "zpardy1@auda.org.au",
            "gender": "Polygender"
          }, {
            "id": 3,
            "first_name": "Guillema",
            "last_name": "Ryan",
            "email": "gryan2@huffingtonpost.com",
            "gender": "Non-binary"
          }, {
            "id": 4,
            "first_name": "Lee",
            "last_name": "McCaughren",
            "email": "lmccaughren3@geocities.jp",
            "gender": "Male"
          }, {
            "id": 5,
            "first_name": "Vivianne",
            "last_name": "Giorgione",
            "email": "vgiorgione4@godaddy.com",
            "gender": "Genderqueer"
          }, {
            "id": 6,
            "first_name": "Vladimir",
            "last_name": "Smoughton",
            "email": "vsmoughton5@angelfire.com",
            "gender": "Non-binary"
          }, {
            "id": 7,
            "first_name": "Nadiya",
            "last_name": "Cattow",
            "email": "ncattow6@yahoo.co.jp",
            "gender": "Female"
          }, {
            "id": 8,
            "first_name": "Carmella",
            "last_name": "Francillo",
            "email": "cfrancillo7@irs.gov",
            "gender": "Bigender"
          }, {
            "id": 9,
            "first_name": "Thurstan",
            "last_name": "Boatswain",
            "email": "tboatswain8@vimeo.com",
            "gender": "Bigender"
          }, {
            "id": 10,
            "first_name": "Baily",
            "last_name": "Rhubottom",
            "email": "brhubottom9@weibo.com",
            "gender": "Polygender"
          }, {
            "id": 11,
            "first_name": "Barnebas",
            "last_name": "Hylands",
            "email": "bhylandsa@nsw.gov.au",
            "gender": "Male"
          }, {
            "id": 12,
            "first_name": "Benn",
            "last_name": "Gudahy",
            "email": "bgudahyb@typepad.com",
            "gender": "Agender"
          }, {
            "id": 13,
            "first_name": "Verney",
            "last_name": "MacSweeney",
            "email": "vmacsweeneyc@shutterfly.com",
            "gender": "Non-binary"
          }, {
            "id": 14,
            "first_name": "Gavra",
            "last_name": "Duckfield",
            "email": "gduckfieldd@yolasite.com",
            "gender": "Female"
          }, {
            "id": 15,
            "first_name": "Hernando",
            "last_name": "ORoan",
            "email": "horoane@prlog.org",
            "gender": "Female"
          }, {
            "id": 16,
            "first_name": "Karoline",
            "last_name": "Ridge",
            "email": "kridgef@prweb.com",
            "gender": "Genderfluid"
          }, {
            "id": 17,
            "first_name": "Kennith",
            "last_name": "Postans",
            "email": "kpostansg@live.com",
            "gender": "Polygender"
          }, {
            "id": 18,
            "first_name": "Saree",
            "last_name": "Gley",
            "email": "sgleyh@canalblog.com",
            "gender": "Genderqueer"
          }, {
            "id": 19,
            "first_name": "Corine",
            "last_name": "Cordey",
            "email": "ccordeyi@bizjournals.com",
            "gender": "Polygender"
          }, {
            "id": 20,
            "first_name": "Dinah",
            "last_name": "Mullins",
            "email": "dmullinsj@technorati.com",
            "gender": "Non-binary"
          }, {
            "id": 21,
            "first_name": "Denni",
            "last_name": "Faers",
            "email": "dfaersk@mysql.com",
            "gender": "Female"
          }, {
            "id": 22,
            "first_name": "Corey",
            "last_name": "Petyankin",
            "email": "cpetyankinl@washingtonpost.com",
            "gender": "Polygender"
          }, {
            "id": 23,
            "first_name": "Milo",
            "last_name": "Dimitrescu",
            "email": "mdimitrescum@biglobe.ne.jp",
            "gender": "Polygender"
          }, {
            "id": 24,
            "first_name": "Norry",
            "last_name": "Lomasna",
            "email": "nlomasnan@google.com",
            "gender": "Female"
          }, {
            "id": 25,
            "first_name": "Jan",
            "last_name": "Bratch",
            "email": "jbratcho@360.cn",
            "gender": "Non-binary"
          }, {
            "id": 26,
            "first_name": "Chandler",
            "last_name": "Kerry",
            "email": "ckerryp@jugem.jp",
            "gender": "Genderqueer"
          }, {
            "id": 27,
            "first_name": "Finley",
            "last_name": "Flipek",
            "email": "fflipekq@columbia.edu",
            "gender": "Genderqueer"
          }, {
            "id": 28,
            "first_name": "Joshua",
            "last_name": "MacMarcuis",
            "email": "jmacmarcuisr@java.com",
            "gender": "Non-binary"
          }, {
            "id": 29,
            "first_name": "Joann",
            "last_name": "Beagan",
            "email": "jbeagans@narod.ru",
            "gender": "Genderqueer"
          }, {
            "id": 30,
            "first_name": "Jozef",
            "last_name": "Dubery",
            "email": "jduberyt@dion.ne.jp",
            "gender": "Male"
          }, {
            "id": 31,
            "first_name": "Carolyne",
            "last_name": "Duxbarry",
            "email": "cduxbarryu@altervista.org",
            "gender": "Bigender"
          }, {
            "id": 32,
            "first_name": "Jarid",
            "last_name": "Cleator",
            "email": "jcleatorv@de.vu",
            "gender": "Genderqueer"
          }, {
            "id": 33,
            "first_name": "Richmound",
            "last_name": "Ferriere",
            "email": "rferrierew@umn.edu",
            "gender": "Agender"
          }, {
            "id": 34,
            "first_name": "Vassily",
            "last_name": "Bernat",
            "email": "vbernatx@smh.com.au",
            "gender": "Male"
          }, {
            "id": 35,
            "first_name": "Thor",
            "last_name": "Castlake",
            "email": "tcastlakey@comsenz.com",
            "gender": "Genderqueer"
          }]', true);
          
    return view('helloLaravel', ['users' => $data]);
    }

}
